### ISSUE TITLE
Namespace value check?

### ISSUE THREAD

**Issue by ncatlett** [OpenBEL/bel.rb#27]
What is the best way to check the namespace value (i.e., confirm it is present in the namespace) given a Parameter? 

The encoding can be retrieved for the Parameter, or the validity of a Term can be checked (if a function is added to the Parameter), but is there a better way?

**Comment by abargnesi** [comment]
You cannot check the validity of a Parameter with an API like `Term.valid?` although this would be useful. A workaround would be to check if the `NamespaceDefinition` includes the namespace value in its domain. Something like:

```ruby
def valid_namespace_value?(parameter)
  return false unless parameter
  if parameter.ns
    parameter.ns.values.include?(parameter.value)
  else
    true
  end
end
```

Use:

```ruby
valid_namespace_value?(Parameter.new(RGD, :AKT1))
# false - AKT1 is not contained with the RGD namespace

valid_namespace_value?(Parameter.new(HGNC, :AKT1))
# true - AKT1 is contained within the HGNC namespace

valid_namespace_value?(Parameter.new(nil, :AKT5))
# true - no namespace available to impose constraints
```

**Comment by abargnesi** [comment]
API `Parameter#valid?` was added to master and merged to next. See README for usage.
