### ISSUE TITLE
bio2rdf: parser issue for strings containing "quote" characters

### ISSUE THREAD

**Issue by juliakozlovsky** [OpenBEL/bel.rb#37]
bio2rdf seems to have issues with parsing stings that contain "escaped" quote characters.

Example:

SET Citation = {"PubMed","Human kidney \"enkephalinase\", a neutral metalloendopeptidase that cleaves active peptides.","6349683","","Gafford JT|Skidgel RA|Erdös EG|Hersh LB","Biochemistry 1983 Jun 21;22(13):3265-71"}

The above generates the following error:

/Library/Ruby/Gems/2.0.0/gems/rdf-1.1.7/lib/rdf/writer.rb:390:in `write_statement': Statement #<RDF::Statement:0x3ff8561fd57c(_:366e52b0-c15e-0132-761e-3c15c2c53e7c <http://www.openbel.org/vocabulary/hasCitation> <http://bio2rdf.org/pubmed: a neutral metalloendopeptidase that cleaves active peptides.> .)> is invalid (RDF::WriterError)
from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:85:in `<<'
from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:67:in `block (2 levels) in initialize'
from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:66:in `each'
from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:66:in `block in initialize'
from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/lib/bel/script.rb:203410:in `yield'
from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/lib/bel/script.rb:203410:in `each'
from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:64:in `each'
from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:64:in `each'
from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:64:in `each'
from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:64:in `initialize'
from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:132:in `new'
from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:132:in `<top (required)>'
from /usr/bin/bel2rdf:23:in `load'
from /usr/bin/bel2rdf:23:in `<main>'

**Comment by abargnesi** [comment]
Julia, thanks for reporting this.

I have identified a bug in the parser with respect to multiple-valued lists (i.e. `SET Citation = { "PubMed", "...", "..." ...}`.). Currently working on a fix.

**Comment by abargnesi** [comment]
Fixed on *master* branch and merged to *next* branch.
