### ISSUE TITLE
bel2rdf: handling of non-standard symbols

### ISSUE THREAD

**Issue by juliakozlovsky** [OpenBEL/bel.rb#40]
Currently, there seem to be issues with certain symbols that may not have a certain ASCII representation (for example, if a symbol was cut-and-pasted from PDF, or other similar issues). Or maybe it is even limited to only a subset of non-ASCII symbols, it's been hard to tell..

Example: 

abundance(mbCompounds:"17-Cyclopropylmethyl-4,5α-epoxy-3-hydroxy-14β-N-[(2′-pyridyl)-carboxamido]morphinan-6-one") directlyIncreases gtpBoundActivity(proteinAbundance(SPAC:P35372))

Currently, the error is:

MacBook-Pro:BEL user$ bel2rdf --bel /Users/file.bel >>test
/Library/Ruby/Gems/2.0.0/gems/rdf-1.1.7/lib/rdf/model/literal.rb:167:in `encode': "\xCE" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /Library/Ruby/Gems/2.0.0/gems/rdf-1.1.7/lib/rdf/model/literal.rb:167:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/rdf-1.1.7/lib/rdf/model/literal.rb:129:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/rdf-1.1.7/lib/rdf/model/statement.rb:116:in `initialize!'
	from /Library/Ruby/Gems/2.0.0/gems/rdf-1.1.7/lib/rdf/model/statement.rb:96:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/rdf-1.1.7/lib/rdf.rb:170:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/rdf-1.1.7/lib/rdf.rb:170:in `Statement'
	from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:85:in `<<'
	from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:67:in `block (2 levels) in initialize'
	from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:66:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:66:in `block in initialize'
	from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/lib/bel/script.rb:124240:in `yield'
	from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/lib/bel/script.rb:124240:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:64:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:64:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:64:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:64:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:132:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/bel-0.3.0/bin/bel2rdf:132:in `<top (required)>'
	from /usr/bin/bel2rdf:23:in `load'
	from /usr/bin/bel2rdf:23:in `<main>'

In the output, the compound name is rendered as:

<http://www.openbel.org/bel/a_mbCompounds_17-Cyclopropylmethyl-4_5%CE%B1-epoxy-3-hydroxy-14%CE%B2-N-_2%E2%80%B2-pyridyl-carboxamidomorphinan-6-one> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.openbel.org/vocabulary/Abundance>

**Comment by abargnesi** [comment]
The exception here was with encoding the object literal of the rdfs:label triples.
