### ISSUE TITLE
error: c is required

### ISSUE THREAD

**Issue by nbargnesi** [OpenBEL/bel.rb#48]
Running [bel upgrade help](https://asciinema.org/a/21550) prints ``error: c is required``. Specifying what ``c`` is would help. E.g., ``Option --changelog is missing`` or something similar.

GNU Grep is a good example to follow. The default behavior without arguments produces little output and lets you know you're missing something.

```console
$ grep
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
```

Only when asking for help explicitly do you get more of it.

```console
$ grep --help
Usage: grep [OPTION]... PATTERN [FILE]...
Search for PATTERN in each FILE or standard input.
PATTERN is, by default, a basic regular expression (BRE).
Example: grep -i 'hello world' menu.h main.c

Regexp selection and interpretation:
  -E, --extended-regexp     PATTERN is an extended regular expression (ERE)
...
```

**Comment by abargnesi** [comment]
I agree with both points. The commands should return descriptive errors, display basic usage, and indicate how to print full help text.

The latest 0.3.0 release depends on the gli gem to structure the subcommands and it is shaping up to be too rigid and complex in my eyes. Might need to simplify the implementation to get a unix-like feel to `bel` command.

**Comment by abargnesi** [comment]
I took a stab ([gist](https://gist.github.com/abargnesi/d678e35635dde1a677e6)) at subcommands using the [trollop module](https://github.com/ManageIQ/trollop/blob/master/lib/trollop.rb) (single file; vendored in tree). Seems to give us the capabilities we need and the reduced complexity/footprint I was after.
