### ISSUE TITLE
change default bel upgrade changelog to latest-release

### ISSUE THREAD

**Issue by nbargnesi** [OpenBEL/bel.rb#49]
The ``-c, --changelog`` argument to ``bel upgrade`` is required but has no default. How about reusing our [latest-release](http://resource.belframework.org/belframework/latest-release/) nomenclature as a default option here?

**Comment by abargnesi** [comment]
That seems like a reasonable default. The user's BEL knowledge will need to reference either `latest-release` or the latest date version (i.e. `20150611`) in order to match the updates in this changelog.

It could get a little confusing.
