### ISSUE TITLE
update namespace 

### ISSUE THREAD

**Issue by ncatlett** [OpenBEL/bel.rb#55]
to include namespaces added in 20150611 release:

MESHC, MESHCID, MESHDID, MESHPPID, MESHCSID

Also check and update prefixes

**Comment by abargnesi** [comment]
I'm wondering if this should be more broadly implemented by leveraging the `BEL::Namespace::ResourceIndex` class to resolve keywords and URLs.

**Comment by abargnesi** [comment]
These were updated in e8df1def50ea912bfc335d5bab15888f17df5fab when I saw the inconsistency.
