### ISSUE TITLE
bel2rdf fails to process short form of activity functions

### ISSUE THREAD

**Issue by ncatlett** [OpenBEL/bel.rb#63]
get error:
/usr/local/lib64/ruby/gems/2.2.0/gems/bel-0.3.1/lib/bel/extensions/rdf/rdf.rb:119:in `to_rdf': undefined method `short_form' for :kin:Symbol (NoMethodError)

**Comment by abargnesi** [comment]
I can't reproduce this by trying the following:

- convert to RDF from parsed BEL script term

    - `BEL::Script.parse("kin(p(HGNC:AKT1))")`)

- convert to RDF directly in ruby

    - `kin(p(HGNC[:AKT1])).to_rdf`

Could you attach some ruby code that raises this error?

**Comment by ncatlett** [comment]
Appears to be working for 0.3.2 and 0.3.3
