### ISSUE TITLE
Integrate the gosh (i.e. go shell)

### ISSUE THREAD

**Issue by abargnesi** [OpenBEL/bel.rb#67]
We should integrate the [gosh](https://github.com/formwork-io/gosh) into the tree to make development commands easily accessible.

Some gosh commands to integrate:

- unit and integration tests (e.g. `rake unit` and `rake integration`)
- ctags generation
- guard (file system monitor) to trigger unit tests

**Comment by nbargnesi** [comment]
Any particulars on ctags/cscope generation?

**Comment by abargnesi** [comment]
I removed cscope, never found much value over ctags. Integration with editors was not great either.

I use ctags within vim to jump around. At some point I had this integrated with the project such that every time you modified a file or updated your installed gems ruby tags will be indexed. It was using the guard gem for filesystem notification.

Check out commit 31717a5087a91e9e9b820fb358e582c57629c4e7 that was never integrated into master.

I think it would be great to have ctag generation for dependencies and project included as a gosh command. Bonus points for another gosh command to kick off guard to do it for you on filesystem notification.

**Comment by nbargnesi** [comment]
Recommend we close this - integration currently lives on next.

**Comment by abargnesi** [comment]
I would rather hold off until we get ctags generation in there. I'll be able to look at this tomorrow.

**Comment by nbargnesi** [comment]
For reference, Sublime Text's _Goto definition_ appears to work w/out any extra work on my part (like a tags file). Again, for reference, not suggesting an alternative.
