### ISSUE TITLE
turtle output format option does not have effect 

### ISSUE THREAD

**Issue by mhsano** [OpenBEL/bel.rb#69]
Using the -f turtle output option does not change the output format compared to the standard n-triples otutput. Maybe the turtle writer constructor needs to be parametrized with prefix/URI hashes (e.g. belv,...).  Also standard prefixes should be written.

**Comment by abargnesi** [comment]
How are you running BEL to RDF conversion?

When running the commands you can do either of the following:

```sh
# (Recommended) Use the bel command with a bel2rdf subcommand.
bel bel2rdf --bel small_corpus.bel --format turtle

# (Deprecated) Use the bel2rdf.rb command.
bel2rdf.rb --bel small_corpus.bel --format turtle
```

There is a soft dependency on the `rdf-turtle` [gem](https://rubygems.org/gems/rdf-turtle). You will receive an error, if this gem is not installed, with instructions on how to install it.

**Comment by mhsano** [comment]
I checked it. The output is in turtle format and the formatting option is correctly recognized.
However - the turtle output produced has only full URIs and no prefixes (e.g. belv:..., rdfs:....,). This limits readability.

It would help if the turtle writer would be parametrized with the standard RDF and  OpenBEL prefix/URI combinations.

**Comment by abargnesi** [comment]
On the docket for 0.3.4. Work should include feature plus refactoring:

- Define comprehensive RDF and BEL prefixes for turtle output. ntriple/nquad formats will be unaffected since they do not support for prefixes.
- Support reading / writing of supported RDF formats within the RDF Format extension and `bel translate` command.
- Allow options to be passed to Format extensions. Pass on through from `bel translate`.

**Comment by abargnesi** [comment]
bel.rb uses [ruby-rdf/rdf](https://github.com/ruby-rdf/rdf) for RDF capabilities. This gem includes [well-known RDF vocabularies](https://github.com/ruby-rdf/rdf/tree/1.99-support/lib/rdf/vocab) as Ruby constants. It would be wise to reuse these definitions and for BEL-specific vocabularies [create our own vocabulary with ruby-rdf/rdf](https://github.com/ruby-rdf/rdf/tree/1.99-support/#using-ad-hoc-rdf-vocabularies).

FYI as part of rdf 2.0.0 they have moved the vocabularies to a [separate gem](https://github.com/ruby-rdf/rdf-vocab). Stick with using version 1.99.1 of the rdf gem.

At a later we can migrate to rdf 2.0.0.

**Comment by abargnesi** [comment]
The [bel_schema.rb file](https://github.com/OpenBEL/bel.rb/blob/master/lib/bel/translator/plugins/rdf/bel_schema.rb#L5-L8) in the rdf translator plugin declares some BEL-specific vocabularies for use with the rdf gem:

```ruby
BELR    = ::RDF::Vocabulary.new('http://www.openbel.org/bel/')
BELV    = ::RDF::Vocabulary.new('http://www.openbel.org/vocabulary/')
BELE    = ::RDF::Vocabulary.new('http://www.openbel.org/evidence/')
PUBMED  = ::RDF::Vocabulary.new('http://bio2rdf.org/pubmed:')
```

**Comment by abargnesi** [comment]
@rumilbaybikov addressed RDF prefixes in PR #115.

**Comment by abargnesi** [comment]
Standardized the command-line option as well in 50f146073c57e3e1a76d7b0f81bebe15e8d2ac46.

**Comment by abargnesi** [comment]
Completed.
